CXX = g++
# CXX_FLAGS = -O3 -flto -I../utils -fno-exceptions -fprefetch-loop-arrays -fno-rtti -fomit-frame-pointer
CXX_FLAGS = -O3 -flto -fomit-frame-pointer -fno-rtti -fno-exceptions -I../utils

SRC = src/main.cpp
OUT = build/median.exe

all: 
	$(CXX) $(CXX_FLAGS) $(SRC) -o $(OUT)